### ISSUE TITLE
Multilevel List - implementation issue

### ISSUE THREAD

**Issue by TrickTrcker** [SortableJS/angular-sortablejs#104]
Hi,
Is it possible to implement drag and drop options for multi level parent and and child?.

**Comment by smnbbrv** [comment]
Yes, it is (I used this in multiple projects for sorting the trees). Just give them the same group name

**Comment by bhaskerchari** [comment]
Hello @smnbbrv ,

Can you please post a sample demo or a plunker showcasing that as I am also facing difficulty in acheiving it when there are multiple nested lists involved.

I am facing difficulty in handling the events properly since they are not firing correctly in few cases. 

Any help is much appreciated.
Thanks in advance,
Bhasker

**Comment by smnbbrv** [comment]
https://github.com/SortableJS/angular-sortablejs/blob/master/README.md#demo

**Comment by benshabatnoam** [comment]
Hello @smnbbrv,

The demo you've linked doesn't have a nested lists example.

Can you explain how can we achieve a functionality like in [sortablejs demo](http://sortablejs.github.io/Sortable/) - section "Nested Sortables Example".

The functionality I mean is:
 1. When dragging "2.1" it won't replace with "2.2" has it has inner items.
 2. When dragging "2.1" inside "2.2" it will change the div to look the save as an "2.2" child.

Thanks,
Noam

**Comment by eherve** [comment]
+1
