### ISSUE TITLE
Different dynamic item sizes on drop-zones

### ISSUE THREAD

**Issue by devlfm** [SortableJS/angular-sortablejs#114]
Hi,

I'm facing an issue here, I have multi-lists, and the main list have bigger items with flex-grow and flex-basis defined by inline css.

The problem here is that the lib only accepts css class, and maybe I could solve my problem if inline-css could be supported on drop-over.

any thoughts?

**Comment by smnbbrv** [comment]
hi @devlfm 

only classes are currently supported because the main library does not provide other ways.

What you can do is pushing your class with custom values dynamically to the head, e.g. look [here](https://stackoverflow.com/questions/1720320/how-to-dynamically-create-css-class-in-javascript-and-apply). You can do it e.g. in onMove event.

**Comment by devlfm** [comment]
Hi @smnbbrv 

Good tip, thank  you. I only hope don't get my header full of style tags ^^, btw should I do this outside of angular with ngZone? or renderer2 can add elements to header too?

**Comment by smnbbrv** [comment]
you can add it with renderer and I don't think you should do it outside angular because onMove does not happen often.

You can always remove style tags after you render next one, so it always remains only one. That's the same how you can remove any HTML element.
