### ISSUE TITLE
Documentation Error?

### ISSUE THREAD

**Issue by invertedspear** [SortableJS/angular-sortablejs#35]
SystemJS configuration instructs to add  "'angular-sortablejs': 'node_modules/angular-sortablejs'" to that map object. But when I do I get a 404 looking for "/node_modules/angular-sortablejs/index.js". After peeking at what was installed into node_modules it looks like the index.js is in the "dist" subfolder. I updated the map object with the dist subfolder which got the package working for me.

Is the documentation correct and did I do something wrong? or is the documentation just missing that subfolder?

**Comment by smnbbrv** [comment]
Hi @invertedspear 

most likely the documentation is wrong because I'm using webpack in my projects and this particular piece of documentation was done once upon a time in the really beginning (there were structural changes after).

Could you update the docs with the proper setup and make a pull request?

I would be grateful for this

**Comment by invertedspear** [comment]
Hey @smnbbrv,

I'm really new to Git and Github. I think I did things right, but since this is a first, please provide some feedback if I didn't.

Thanks

**Comment by smnbbrv** [comment]
Hi @invertedspear 

thank you for you contribution, everything is fine 👍
