### ISSUE TITLE
Uncaught ReferenceError: exports is not defined at eval

### ISSUE THREAD

**Issue by brettnew** [SortableJS/angular-sortablejs#50]
Hi, I am getting the following error:
```
Uncaught ReferenceError: exports is not defined
    at eval (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:5:23)
    at eval (<anonymous>)
    at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9)
```

Application still works, would just like to fix this in case it causes trouble later on. Thanks.

**Comment by smnbbrv** [comment]
that's weird. Do you have / can you create a demo app representing the issue?

**Comment by brettnew** [comment]
I've created this very simple [app](https://github.com/brettnew/angular-sortablejs-example)- once you serve it and open the console, you will see this error:
![image](https://user-images.githubusercontent.com/19401267/31829131-02b3cf68-b582-11e7-91e6-5ac842c6a210.png)

When I remove these two lines from the `.angular-cli.json` file, I no longer get the error and the sorting seems to work, but your documentation seems to indicate that they are necessary, so I am leery about leaving them out.
```
"../node_modules/angular-sortablejs/dist/",
"../node_modules/sortablejs/Sortable.min.js"
```

Any further advice you could give on this would be really appreciated.

**Comment by smnbbrv** [comment]
Oh my god! The documentation says to include the paths for System.js while angular-cli is fully Webpack-based.

That's definitely my fault too. Sorry for that, it's really sad that you have a problem because of some missing documentation. Just moved that shitty SystemJS to the bottom of the page.

Please, remove them from your angular-cli configuration.

If you feel the issue as resolved, feel free to close it 👍

**Comment by brettnew** [comment]
Ok, thanks.
